# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml
permalink: pretty
name: website
tagline: 'Developer, designer and dreamer'
description: 'Developer by day, designer by noon and dreamer by night'
#url: http://harshakumar.in
#domain: harshakumar.in
baseurl:
author:
name: 'Harsha Kumar'
gpage: +HarshaKumarDotIn
email: contact@harshakumar.in
avatar: /author-bw.jpg
youtube: enchantingstrings
# Google analytics track id
google_analytics: "UA-42422649-1"
# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
'**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'Thumbs.db']
include: ['.htaccess']
# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
# Markdown library
markdown: kramdown
# auto_ids: true
# footnote_nr: 1
# entity_output: as_char
# toc_levels: 1..6
# use_coderay: false
# coderay:
# coderay_wrap: div
# coderay_line_numbers: inline
# coderay_line_numbers_start: 1
# coderay_tab_width: 4
# coderay_bold_every: 10
# coderay_css: style
pygments: true
# Path to assets
css: /assets/css
img: /assets/img
js: /assets/js
fonts: /assets/fonts
